/cpp_lane_line_detection:
  ros__parameters:
    # 相机内参矩阵
    camera_matrix:
    - 1156.60712
    - 0.0
    - 668.960301
    - 0.0
    - 1151.64235
    - 388.057003
    - 0.0
    - 0.0
    - 1.0
    # 畸变系数
    dist_coeff:
    - -0.23185387
    - -0.11832052
    - -0.00116561
    - 0.00023902
    - 0.15356154
    use_sim_time: false
    image_sub_topic_name: /camera/image_raw


    # 参数名称及值必须统一对齐，值无法使用多维列表
